### ISSUE TITLE
Implement NSObject/NSCoding for Models

### ISSUE THREAD

**Issue by calvcoll** [MastodonKit/MastodonKit#29]
Unfortunately currently this does not support NSObject/NSCoding protocols, and hence saving these objects easily to disk is unavailable. (For example caching objects locally easily with NSKeyedArchiver/NSKeyedUnarchiver).

If you could add support this would be great! c:

**Comment by ornithocoder** [comment]
I recently merged into master - I'll update the .podspec later this week - a big commit that changes all the models to conform to Swift 4's Codable (Encodable & Decodable protocols). Let me know if this is good enough for you.

**Comment by calvcoll** [comment]
Hi, thanks this should be more than enough! Thanks for all the effort!
