### ISSUE TITLE
MastodonKit: Command PhaseScriptExecution failed with a nonzero exit code.

### ISSUE THREAD

**Issue by ResourceHog** [MastodonKit/MastodonKit#45]
The following output occurs when I try to build right after I install MastodonKit with cocoapods.

> PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/<redacted>/Library/Developer/Xcode/DerivedData/MastoViewer-bbrxmmfrxvitfphfpplcvznwejfo/Build/Intermediates.noindex/MastoViewer.build/Debug/MastoViewer.build/Script-1E315CD213184982319E532E.sh (in target: MastoViewer)
>     cd /Users/<redacted>/Documents/macOSAPP/MastoViewer
>     /bin/sh -c /Users/<redacted>/Library/Developer/Xcode/DerivedData/MastoViewer-bbrxmmfrxvitfphfpplcvznwejfo/Build/Intermediates.noindex/MastoViewer.build/Debug/MastoViewer.build/Script-1E315CD213184982319E532E.sh
> 
> mkdir -p /Users/<redacted>/Library/Developer/Xcode/DerivedData/MastoViewer-bbrxmmfrxvitfphfpplcvznwejfo/Build/Products/Debug/MastoViewer.app/Contents/Frameworks
> rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/<redacted>/Library/Developer/Xcode/DerivedData/MastoViewer-bbrxmmfrxvitfphfpplcvznwejfo/Build/Products/Debug/MastodonKit/MastodonKit.framework" "/Users/<redacted>/Library/Developer/Xcode/DerivedData/MastoViewer-bbrxmmfrxvitfphfpplcvznwejfo/Build/Products/Debug/MastoViewer.app/Contents/Frameworks"
> building file list ... done
> MastodonKit.framework/
> MastodonKit.framework/MastodonKit -> Versions/Current/MastodonKit
> MastodonKit.framework/Resources -> Versions/Current/Resources
> MastodonKit.framework/Versions/
> MastodonKit.framework/Versions/Current -> A
> MastodonKit.framework/Versions/A/
> MastodonKit.framework/Versions/A/MastodonKit
> MastodonKit.framework/Versions/A/Resources/
> MastodonKit.framework/Versions/A/Resources/Info.plist
> 
> sent 629251 bytes  received 106 bytes  1258714.00 bytes/sec
> total size is 628754  speedup is 1.00
> /Users/<redacted>/Documents/macOSAPP/MastoViewer/Pods/Target Support Files/Pods-MastoViewer/Pods-MastoViewer-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
> Command PhaseScriptExecution failed with a nonzero exit code
> 

![mastodonki](https://user-images.githubusercontent.com/3767092/45911946-eeac9300-bdce-11e8-99d2-a7111f085f58.png)

my Podfile looks like this: 

```
# Uncomment the next line to define a global platform for your project
# platform :osx, '10.10'

target 'MastoViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MastoViewer
    pod 'MastodonKit', '~> 1.0'

  target 'MastoViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MastoViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TootViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TootViewer

end

```

Platform is osx 10.13.6
xcode version 10.0 (10A255)

What does this mean?

**Comment by gabek** [comment]
@ResourceHog It's likely a code signing setup issue.  Go to your project settings and make sure either automatic signing is enabled, or your manual signing setup is fully configured.

**Comment by ResourceHog** [comment]
Oh yes this fixed my issue.
